development:
  access_key_id: your-access-key
  secret_access_key: your-secret-access-key
  bucket: paperclip-s3

test:
  access_key_id: your-access-key
  secret_access_key: your-secret-access-key
  bucket: paperclip-s3